### ISSUE TITLE
Update text in portal tutorial page

### ISSUE THREAD

**Issue by grungle** [iDigBio/idb-portal#1]
If this can be updated, then we can close redmine ticket 628
Spelling error "successfully"
Add "and is supported for"

idb-portal/app/views/tutorial.html

[line24]
 <p>
                The iDigBio Portal requires the use of an HTML5 compliant browser with cookies enabled. The Portal has been tested successfully against, and is supported for, the following browsers:<br>
                <b>Chrome</b><br>
                <b>Firefox</b><br>
                <b>Safari</b><br>
                <b>Internet Explorer</b> 10,11<br>
              </p>
[line30]

**Comment by gete76** [comment]
done
