### ISSUE TITLE
No coordinates should not equal 0,0

### ISSUE THREAD

**Issue by rukayaj** [iDigBio/idb-portal#37]
This record is published without coordinates - https://www.gbif.org/occurrence/199452881, but appears on iDigBio's map as having 0 in the decimalLatitude and decimalLongitude fields, and is therefore showing up on the map incorrectly. Is it putting in default values when it imports from GBIF?

Edit:  Sorry, here is the link on iDigBio: https://www.idigbio.org/portal/records/d94e148c-e100-4a03-bdb2-e5345fb6a309

**Comment by roncanepa** [comment]
Thank you for submitting an issue!  We'll have to take a look to see what might be going on.

**Comment by danstoner** [comment]
We see decimalLatitude value of 0 is being supplied.

iDigBio does not import from GBIF, we pull from the data publisher's IPT itself:

https://ipt.gbif.no/resource?r=o_fish

It is possible our version is of that record out-of-date.  iDigBio Last Ingested Date: 2019-09-23

It looks like that IPT has upgraded or changed some urls and we are not finding the updated versions.

**Comment by danstoner** [comment]
Yes, we will need to update our ingestion location to target the new publishing location. The currently published dataset does not contain decimalLatitude at all.

**Comment by danstoner** [comment]
@rukayaj  We updated our copy of the published data. I verified that the record in question no longer contains erroneous geo fields such as `decimalLatitude`.

https://www.idigbio.org/portal/records/d94e148c-e100-4a03-bdb2-e5345fb6a309

Thanks again for your report of the issue.

Closing.
